---
# author: lework

- name: configure | Create redis group.
  group: name={{ redis_user }}

- name: configure | Create redis user.
  user: name={{ redis_user }} group={{ redis_user }} shell=/sbin/nologin

- name: configure | Create redis db Directory
  file: path={{ redis_dbdir }} state=directory owner={{ redis_user }} group={{ redis_user }}

- name: configure | Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_dir_path }}/redis.conf"
    mode: 0644
    owner: "{{ redis_user }}"
    group: "{{ redis_user }}"

- name: configure | Ensure Redis daemon shell  is configured.
  template:
    src: redis.sh.j2
    dest: "/etc/rc.d/init.d/{{ redis_daemon }}"
    mode: 0755

- name: configure | Add redis services.
  shell: "chkconfig --add {{ redis_daemon }}  && chkconfig {{ redis_daemon }} on"

- name: configure | Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
