---
# author: lework

- name: Include tomcat8 variables.
  include_vars: tomcat8.yml
  when: tomcat_version | regex_search("^8\.")
  
- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: logrotate.yml
