loveserver-mysql:
  image: 'mysql:5.7.22'
  restart: always
  ports:
    - '13306:3306'
  volumes:
    - /opt/docker/mysql/loveserver-db:/var/lib/mysql
  environment:
     MYSQL_ROOT_PASSWORD: 123456

loveserver-redis:
  image: 'redis:2.8.23'
  restart: always
  ports:
    - '16379:6379'

loveserver-centos-ssh:
  image: 'centos-ssh:7'
  restart: always
  privileged: true
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  ports:
    - '1080:80'
    - '1022:22'
  links:
    - loveserver-mysql:mysql-db
    - loveserver-redis:redis-db
