---
# author: lework

# 1. 进行发布前检查，发布所需要的内容不存在时停止执行并抛出错误信息
- include: check.yml
  when: not deploy_rollback
# 2. 发布代码到目标服务器
- include: deploy.yml
  when: not deploy_rollback
# 3. 确认代码发布后，是否正常运行
- include: verify.yml
  when: not deploy_rollback
# 4. 备份文件。
- include: backup.yml
  when: not deploy_rollback
# 是否回滚
- include: rollback.yml
  when: deploy_rollback