--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: haproxy install
    yum: state=latest name=haproxy

  - name: Make sure a service is running
    systemd: 
      state: started 
      name: haproxy
    tags: haproxy_service_running

  - name: enable service and ensure it is not masked
    systemd:
      name: haproxy
      enabled: yes
      masked: no
    tags: haproxy_service_start
