---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: wget td-agent-3.2.0-0.el7.x86_64.rpm
    get_url: url=http://packages.treasuredata.com.s3.amazonaws.com/3/redhat/7/x86_64/td-agent-3.2.0-0.el7.x86_64.rpm dest=/data0/src/
    tags: wget_td_agent_packages

  - name: td-agent install
    shell: yum install /data0/src/td-agent-3.2.0-0.el7.x86_64.rpm
    ignore_errors: yes
    tags: install_td_agent_packages

  - name: rsync td-agent.conf 
    copy:
      src: files/td-agent.conf
      dest: /etc/td-agent/td-agent.conf
      owner: root
      group: root
      mode: 0664
    notify: restart td-agent
    tags: rsync_fluent_config

  - name: mkdir td-agent data and log dir
    file:
      path: /data0/td-agent/{{ item }}
      owner: td-agent
      group: td-agent
      mode: 0755
      state: directory
    with_items:
      - data
      - logs
    tags: create_fluentd_work_dir

  - name: install fluent plugins
    shell: /opt/td-agent/embedded/bin/fluent-gem install {{ item }}
    with_items:
      - fluent-plugin-input-gelf
      - fluent-plugin-rewrite-tag-filter
      - fluent-plugin-record-reformer
    tags: install_fluent_plugins

  - name: make sure a service is running
    systemd: state=started name=td-agent
    tags: start_service

  - name: enable service and ensure it is not masked
    systemd:
      name: td-agent
      enabled: yes
      masked: no
    tags: service_boot

  handlers:
    - name: restart td-agent
      service: name=td-agent enabled=yes state=restarted
