---
- hosts: all
  become: true
  become_user: root
  remote_user: root
  gather_facts: true
  tasks:
  - name: RedHat os elasticsearch install
    include: "install_jdk_redhat.yml"
    when:
      - ansible_os_family == "RedHat"
    tags: install_jdk_redhat

  #- name: RedHat - add Elasticsearch repo
  # copy: 
  #    src: files/elasticsearch.repo
  #    dest: /etc/yum.repos.d/elasticsearch.repo
  #  tags: add_es_repo

  #- name: RedHat - add Elasticsearch key
  #  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
  #  tags: add_es_repo_key

  #- name: Elasticsearch packages install
  #  yum: state=latest name=elasticsearch
  #  tags: install_es_packages

  - name: rsync es packages
    copy: 
      src: files/elasticsearch-5.6.7.rpm
      dest: /data0/src/elasticsearch-5.6.7.rpm
    tags: rsync_es_packages

  - name: install elasticsearch-5.6.7.rpm
    shell: rpm -ivh /data0/src/elasticsearch-5.6.7.rpm
    ignore_errors: yes
    tags: install_es_packages
    
  - name: mkdir es data and log dir
    file:
      path: /data0/elasticsearch/{{ item }}
      owner: elasticsearch
      group: elasticsearch
      mode: 0755
      state: directory
    with_items:
      - data
      - logs
    tags: create_es_work_dir

  - name: remove old es dir
    file:
      path: /var/lib/elasticsearch/
      owner: root
      group: root
      mode: 0755
      state: absent
      backup: yes
    tags: remove_old_es_work_dir

  - name: mkdir es data link
    file:
      src: /data0/elasticsearch/data
      dest: /var/lib/elasticsearch
      owner: elasticsearch
      group: elasticsearch
      mode: 0755
      state: link
    tags: create_es_work_dir_link

  - name: rsync elasticsearch.yml
    template:
      src: files/elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: root
      mode: 0664
    tags: rsync_es_conf

  - name: Make sure a service is running
    systemd: 
      state: started 
      name: elasticsearch
    tags: es_service_running

  - name: enable service elasticsearch and ensure it is not masked
    systemd:
      name: elasticsearch
      enabled: yes
      masked: no
    tags: es_service_start
