--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: clean files
    file: name={{ item }} state=absent
    with_items:
    - "/usr/local/node"
    - "/usr/bin/node"
    - "/usr/bin/npm"
    - "/usr/bin/cnpm"
