---
# author: lework

- name: configure | Create etcd Directory.
  file: path={{ item }} state=directory
  with_items:
   - "{{ etcd_datadir }}"
   - "{{ etcd_wardir }}"

- name: configure | Setup etcd.conf file.
  template:
    dest: "{{ etcd_datadir }}/etcd.conf"
    mode: 0644
    src: etcd.conf.j2
