#!/bin/sh
REPOS="$1"
REV="$2"
export LC_CTYPE="en_US.UTF-8"
export LC_ALL=

LOGPATH="/app/log"
[ ! -d ${LOGPATH} && mkdir -p ${LOGPATH} ]
SVNBIN="/usr/bin/svn"
$SVNBIN update --username admin --password admin /data/web/www
if [ $? -eq 0 ]
	then
		/usr/bin/rsync -az --delete /data/web/www /tmp
fi
