---
# author: lework

- name: Configtest nginx.
  shell: /etc/rc.d/init.d/openresty configtest

- name: Reload nginx - after config check.
  shell: /etc/rc.d/init.d/openresty reload

- name: Reload nginx.
  debug: msg="checking config first"
  changed_when: True
  notify: 
   - Configtest nginx.
   - Reload nginx - after config check.
