---
# author: lework

- name: install_from_rpm | Install the php repo.
  yum: "name={{ php_rpm_url }} state=present"
    
- name: install_from_rpm | Ensure PHP packages are installed.
  package: "name={{ item }} state=installed"
  with_items: "{{ php_rpm }}"