---
# author: lework

vsftpd_packages:
  - vsftpd
  - libsemanage-python
  - libselinux-python
  - pam
  - db4-utils
  
vsftpd_listen_port: 21
vsftpd_data_port: 20
vsftpd_pasv_min_port: 30000
vsftpd_pasv_max_port: 31000

vsftpd_local_umask: '022'
vsftpd_share_path: '/ftp_share'
vsftpd_banner: "Welcome to Ftp Server!"
vsftpd_syslog_enable: false

vsftpd_log_file: '/var/log/vsftpd.log'
vsftpd_xferlog_file: '/var/log/xferlog'

vsftpd_options: ""
# vsftpd_options: |
#   max_per_ip: 5
#   max_clients: 100
vsftpd_anon: true
vsftpd_local_users: []
# vsftpd_users:
#  - name: alice
#    password: "ecila"
#    home: /ftp_alice

vsftpd_vusers: []
# vsftpd_vusers:
#  - name: alice
#    password: ecila
#    local_root: '/alice_share'
#    conf: |
#      local_umask=011

vsftpd_userfile: "/etc/vsftpd/vuser"
vsftpd_userdb: "/etc/vsftpd/vuser.db"
vsftpd_userconf: "/etc/vsftpd/vuser_conf"