---
# author: lework

software_files_path: "/opt/software"
software_install_path: "/usr/local"

sersync_version: "2.5.4"

sersync_file: "sersync{{ sersync_version }}_64bit_binary_stable_final.tar.gz"
sersync_file_path: "{{ software_files_path }}/{{ sersync_file }}"
sersync_file_url: "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/sersync/{{ sersync_file }}"

sersync_xfs: "false"
sersync_exclude: [] # ["*.ini","*.txt"]
sersync_logpath: /var/log/sersync
sersync_conf: /usr/local/sersync/conf

sersync_watch: "" # /data/
sersync_rsync: {} # {"ip":192.168.77.130, "port":873, "name":data1, "user":t1, "pass":123456,"params":"-artuz"}
sersync_rsync_logfile: "{{ sersync_logpath }}/sersync_rsync_exec.log"
sersync_rsync_passwordfile: "{{ sersync_conf }}/sersync_rsync.password"
sersync_rsync_timeout: 100
sersync_rsync_ssh: "false"
sersync_failLog: "{{ sersync_logpath }}/rsync_fail_log.sh"

sersync_inotify_delete: true
sersync_inotify_createFolder: true
sersync_inotify_createFile: false
sersync_inotify_closeWrite: true
sersync_inotify_moveFrom: true
sersync_inotify_moveTo: true
sersync_inotify_attrib: false
sersync_inotify_modify: false

sersync_crontab: false
sersync_schedule: 600
ansible_python_interpreter: /usr/bin/python2.6
