---
- hosts: all
  remote_user: root

  tasks:
  # Requires ansible 1.8+
  - name: 'YUM - fire and forget task'
    yum: name=docker-io state=installed
    async: 1000
    poll: 0
    register: yum_sleeper

  - name: 'YUM - check on fire and forget task'
    async_status: jid={{ yum_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 30